services:
  - type: web
    name: laravel-portfolio
    env: php
    plan: free
    rootDir: public
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000

    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

